name: I14Y Harvester OGD Office Fédéral de Statistique catalogue ABN

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  harvest-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download previous data
      uses: dawidd6/action-download-artifact@v4
      continue-on-error: true
      with:
          name: dataset_ids
          workflow: OGD_OFS.yml
          workflow_conclusion: success
          if_no_artifact_found: warn
          path: OGD_OFS/data
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run harvester script
      env:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
      run: python src/harvester_ABN.py
    
    - name: Upload log
      uses: actions/upload-artifact@v4
      with:
        name: harvest-log
        path: harvest_log.txt

    - name: Upload updated data
      uses: actions/upload-artifact@v4
      with:
        name: dataset_ids
        path: OGD_OFS/data/dataset_ids.json
        retention-days: 2
